

USE Sales;
ALTER DATABASE Sales
MODIFY FILEGROUP [PRIMARY] DEFAULT;
GO

CREATE UNIQUE CLUSTERED INDEX Kek ON Sales.Products  (ID, name, price) ON [primary]
GO

ALTER DATABASE Sales
REMOVE FILE sales1dat;
GO
ALTER DATABASE Sales
REMOVE FILEGROUP SalesFG;
GO
